#Requires AutoHotkey v2.0 64-bit

#Include TSEnums.ahk

/**
 * A tree-sitter language module
 */
class TSLanguage {

    /**
     * The name of this language. This is `NULL` in older parsers.
     * @type {String}
     */
    Name => DllCall("tree-sitter\ts_language_name", "ptr", this, "cdecl astr")
    
    /**
     * The number of valid states in this language.
     * @type {Integer}
    */
    StateCount => DllCall("tree-sitter\ts_language_state_count", "ptr", this, "cdecl uint")

    /**
     * The number of distinct node types in the language. Note that this does not include the ERROR nodes.
     * @type {Integer}
     */
    SymbolCount => DllCall("tree-sitter\ts_language_symbol_count", "ptr", this, "cdecl uint")

    /**
     * The number of distinct field names in the language.
     */
    FieldCount => DllCall("tree-sitter\ts_language_field_count", "ptr", this, "cdecl uint")

    /**
     * The ABI version number for this language. This version number is used
     * to ensure that languages were generated by a compatible version of
     * Tree-sitter.
     * @type {Integer}
     */
    AbiVersion => DllCall("tree-sitter\ts_language_abi_version", "ptr", this, "cdecl uint")

    /**
     * The language version as a SemVer string
     */
    LanguageVersion {
        get {
            metadata := DllCall("tree-sitter\ts_language_metadata", "ptr", this, "cdecl ptr")
            return Format("{1}.{2}.{3}", 
                NumGet(metadata, 0, "uchar"), 
                NumGet(metadata, 1, "uchar"), 
                NumGet(metadata, 2, "uchar"))
        }
    }

    /**
     * Creates a new TSLanguage
     * @param {Integer} ptr the pointer obtained by calling your language-specific dll's initializer 
     */
    __New(ptr) {
        this.ptr := ptr
    }

    /**
     * Get the field name string for the given numerical id.
     * 
     * @param {Integer} field the field Id
     * @returns {String} the name of the field
     */
    GetFieldName(field) {
        if(!IsInteger(field))
            throw TypeError("Expected an Integer but got a(n) " Type(field), -1, field)

        return DllCall("tree-sitter\ts_language_field_name_for_id", 
            "ptr", this, 
            "ushort", Integer(field),
            "cdecl astr")
    }

    /**
     * Get the numerical id for the given field name string.
     * 
     * @param {String} fieldName the name of the field
     * @returns {Integer} the field's numerical id
     */
    GetFieldId(fieldName) {
        if(!(fieldName is String))
            throw TypeError("Expected a String but got a(n) " Type(fieldName), -1, fieldName)

        return DllCall("tree-sitter\ts_language_symbol_type", 
            "ptr", this, 
            "astr", fieldName,
            "uint", StrLen(fieldName),
            "cdecl ushort")
    }

    /**
     * Get a list of all supertype symbols for the language
     * 
     * @returns {Array<Integer>} a list of all supertype symbols
    */
    GetSupertypes() {
        arrPtr := DllCall("tree-sitter\ts_language_supertypes", "ptr", this, "uint*", &len := 0, "cdecl ptr")

        arr := Array(), arr.Length := len
        Loop(len) {
            arr[A_Index] := NumGet(arrPtr, 2 * (A_Index - 1), "ushort")
        }

        return arr
    }

    /**
     * Get a list of all subtype symbol ids for a given supertype symbol.
     *
     * See `GetSupertypes` for fetching all supertype symbols.
     * 
     * @param {Integer} symbol the symbol to check
     * @returns {Array<Integer>} a list of all symbols which are a subtype of the input
     */
    GetSubtypes(symbol) {
        if(!IsInteger(symbol))
            throw TypeError("Expected an Integer but got a(n) " Type(symbol), -1, symbol)

        arrPtr := DllCall("tree-sitter\ts_language_subtypes", 
            "ptr", this,
            "ushort", Integer(symbol),
            "uint*", &len := 0, 
            "cdecl ptr")

        arr := Array(), arr.Length := len
        Loop(len) {
            arr[A_Index] := NumGet(arrPtr, 2 * (A_Index - 1), "ushort")
        }

        return arr
    }

    /**
     * Get a node type string for the given numerical id.
     * 
     * @param {Integer} symbol the numeric id of the symbol 
     * @returns {String} the name of the symbol
     */
    GetSymbolName(symbol) {
        if(!IsInteger(symbol))
            throw TypeError("Expected an Integer but got a(n) " Type(symbol), -1, symbol)

        return DllCall("tree-sitter\ts_language_symbol_name", 
            "ptr", this, 
            "ushort", Integer(symbol), 
            "cdecl astr")
    }

    /**
     * Check whether the given node type id belongs to named nodes, anonymous nodes,
     * or a hidden nodes.
     *
     * See also `IsSymbolNamed`. Hidden nodes are never returned from the API.
     * @param {Integer} symbol the numeric id of the symbol 
     * @returns {TSSymbolType} the symbol type
     */
    GetSymbolType(symbol) {
        if(!IsInteger(symbol))
            throw TypeError("Expected an Integer but got a(n) " Type(symbol), -1, symbol)

        return DllCall("tree-sitter\ts_language_symbol_type", 
            "ptr", this, 
            "ushort", Integer(symbol), 
            "cdecl uint")
    }

    /**
     * Get the numerical id for the given node type string.
     * 
     * @param {String} symbolName the name of the symbol
     * @returns {Integer} the numerical id of the symbol, or 0 if it is not named
     */
    GetSymbolId(symbolName) {
        if(!(symbolName is String))
            throw TypeError("Expected a String but got a(n) " Type(symbolName), -1, symbolName)

        return DllCall("tree-sitter\ts_language_symbol_for_name",
            "ptr", this,
            "astr", symbolName,
            "uint", StrLen(symbolName),
            "uchar", 1,
            "cdecl ushort")
    }

    /**
     * Get the next parse state. Combine this with lookahead iterators to generate
     * completion suggestions or valid symbols in error nodes. Use `TSNode.GrammarSymbol` 
     * for valid symbols.
     * ts_language_next_state(const TSLanguage *self, TSStateId state, TSSymbol symbol);
     * 
     * @param {Integer} stateId the current state
     * @param {Integer} symbol the current symbol
     * @returns {Integer} the next parse state
    */
    GetNextState(stateId, symbol) {
        if(!IsInteger(stateId))
            throw TypeError("Expected an Integer but got a(n) " Type(stateId), -1, stateId)

        if(!IsInteger(symbol))
            throw TypeError("Expected an Integer but got a(n) " Type(symbol), -1, symbol)

        return DllCall("tree-sitter\ts_language_next_state",
            "ptr", this,
            "uchar", Integer(stateId),
            "uchar", Integer(symbol),
            "cdecl uchar")
    }

    /**
     * Returns a Lookahead iterator which can be used to enumerate the possible states following
     * some other state
     * 
     *      for(symbol, name in lang.Lookahead(currentState)) { ... }
     * 
     * @param {Integer} state the state to look ahead from 
     */
    Lookahead(state) => TSLanguage.LookaheadIterator(this.ptr, state)

    __Delete() {
        DllCall("tree-sitter\ts_language_delete", "ptr", this, "cdecl")
    }

    /**
     * Supports iteration over valid states following some other state
     */
    class LookaheadIterator {

        CurrentSymbol => DllCall("tree-sitter\ts_lookahead_iterator_current_symbol", 
            "ptr", this, 
            "cdecl uchar")

        CurrentSymbolName => DllCall("tree-sitter\ts_lookahead_iterator_current_symbol_name", 
            "ptr", this, 
            "cdecl astr")

        __New(lang, state) {
            this.ptr := DllCall("tree-sitter\ts_lookahead_iterator_new",
                "ptr", lang,
                "uchar", state,
                "cdecl ptr")
        }

        Next() => DllCall("tree-sitter\ts_lookahead_iterator_next", "ptr", this, "cdecl uchar")

        /**
         * Supports enumeration
         */
        Call(&symbol, &name := "") {
            ; There were no possible states
            if(this.ptr == 0 || !this.Next())
                return false

            symbol := this.CurrentSymbol
            name := this.CurrentSymbolName

            return true
        }

        __Delete() => DllCall("tree-sitter\ts_lookahead_iterator_delete", "ptr", this, "cdecl")
    }
}